services:
  db:
    image: postgres:17-alpine
    container_name: bell_vault_db
    env_file: .env.dev
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_HOST: ${DB_HOST:-localhost}
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - /var/lib/postgresql/data
